/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CA2;

/* Class: DIT/FT/1B/02
 * Admission Number: 2212562
 * Name: Chen Lexuan
 */
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ComicRentalFrame extends javax.swing.JFrame {

    /**
     * Creates new form ComicRentalFrame
     */
    private RentalReadWriteFromFile RW = new RentalReadWriteFromFile();
    private RentalSystem RS = new RentalSystem();
    private int ComicIndex;
    private int RenteeIndex;
    String header[] = new String[]{"ISBN-13", "Title", "Rental Per Day", "Deposit Fee"};
    DefaultTableModel dtm;

    public ComicRentalFrame() {
        initComponents();
        ComicIndex = 0;
        RenteeIndex = 0;
        dtm = new DefaultTableModel(header, 0);
        tblRentee.setModel(dtm);
        ComicResult(ComicIndex);
        RenteeResult(RenteeIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelComic = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRental = new javax.swing.JTextField();
        txtDeposit = new javax.swing.JTextField();
        btnComicPrevious = new javax.swing.JButton();
        btnComicNext = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaInfo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        PanelRentee = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRentee = new javax.swing.JTable();
        txtMemberID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnRenteePrevious = new javax.swing.JButton();
        btnRenteeNext = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMsg = new javax.swing.JTextArea();
        btnEarningStats = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rbComic = new javax.swing.JRadioButton();
        rbMember = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnSaveExit = new javax.swing.JButton();
        lblComic = new javax.swing.JLabel();
        lblRentee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelComic.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ISBN-13:");

        txtISBN.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Title:");

        txtTitle.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Daily Rental Cost:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Deposit:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Additional Information:");

        txtRental.setEditable(false);

        txtDeposit.setEditable(false);

        btnComicPrevious.setText("Previous");
        btnComicPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComicPreviousActionPerformed(evt);
            }
        });

        btnComicNext.setText("Next");
        btnComicNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComicNextActionPerformed(evt);
            }
        });

        txtAreaInfo.setEditable(false);
        txtAreaInfo.setColumns(20);
        txtAreaInfo.setRows(5);
        jScrollPane3.setViewportView(txtAreaInfo);

        javax.swing.GroupLayout PanelComicLayout = new javax.swing.GroupLayout(PanelComic);
        PanelComic.setLayout(PanelComicLayout);
        PanelComicLayout.setHorizontalGroup(
            PanelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComicLayout.createSequentialGroup()
                .addGroup(PanelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComicLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(PanelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelComicLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(txtTitle))
                            .addGroup(PanelComicLayout.createSequentialGroup()
                                .addGroup(PanelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRental, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(PanelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelComicLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtDeposit)))))
                    .addGroup(PanelComicLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(PanelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(PanelComicLayout.createSequentialGroup()
                                .addComponent(btnComicPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComicNext))))
                    .addGroup(PanelComicLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtISBN)))
                .addContainerGap())
        );
        PanelComicLayout.setVerticalGroup(
            PanelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(PanelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelComicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComicPrevious)
                    .addComponent(btnComicNext))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Comic Rental System");

        PanelRentee.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Member-ID:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Name:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("List of Loans:");

        tblRentee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN-13", "Title", "Rental Per Day", "Deposit Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRentee);

        txtMemberID.setEditable(false);

        txtName.setEditable(false);

        btnRenteePrevious.setText("Previous");
        btnRenteePrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenteePreviousActionPerformed(evt);
            }
        });

        btnRenteeNext.setText("Next");
        btnRenteeNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenteeNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRenteeLayout = new javax.swing.GroupLayout(PanelRentee);
        PanelRentee.setLayout(PanelRenteeLayout);
        PanelRenteeLayout.setHorizontalGroup(
            PanelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRenteeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRenteeLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelRenteeLayout.createSequentialGroup()
                        .addGroup(PanelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRenteeLayout.createSequentialGroup()
                                .addGroup(PanelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(PanelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                                    .addComponent(txtMemberID)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRenteeLayout.createSequentialGroup()
                                .addComponent(btnRenteePrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRenteeNext)))
                        .addGap(66, 66, 66))))
        );
        PanelRenteeLayout.setVerticalGroup(
            PanelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRenteeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(PanelRenteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRenteePrevious)
                    .addComponent(btnRenteeNext))
                .addGap(14, 14, 14))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "System Message", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtAreaMsg.setEditable(false);
        txtAreaMsg.setColumns(20);
        txtAreaMsg.setLineWrap(true);
        txtAreaMsg.setRows(5);
        jScrollPane1.setViewportView(txtAreaMsg);

        btnEarningStats.setBackground(new java.awt.Color(0, 0, 255));
        btnEarningStats.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEarningStats.setForeground(new java.awt.Color(255, 255, 255));
        btnEarningStats.setText("Get Earning Stats");
        btnEarningStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEarningStatsActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 0, 255));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear Message");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnEarningStats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEarningStats, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClear, btnEarningStats});

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        buttonGroup1.add(rbComic);
        rbComic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbComic.setSelected(true);
        rbComic.setText("Comic by ISBN-13");

        buttonGroup1.add(rbMember);
        rbMember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbMember.setText("Rentee by MemberID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Search:");

        btnSearch.setBackground(new java.awt.Color(0, 153, 51));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rbComic, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(rbMember, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 121, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbComic)
                    .addComponent(rbMember))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        btnSaveExit.setBackground(new java.awt.Color(255, 0, 51));
        btnSaveExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveExit.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveExit.setText("Save & Exit");
        btnSaveExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveExitActionPerformed(evt);
            }
        });

        lblComic.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComic.setText("Comic 1 of 4");

        lblRentee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRentee.setText("Rentee 1 of 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelComic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelRentee, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSaveExit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblComic, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)
                        .addComponent(lblRentee, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComic, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRentee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelRentee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelComic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtAreaMsg.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnComicNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComicNextActionPerformed
        // TODO add your handling code here:
        try {
            ComicIndex += 1;
            if (ComicIndex >= RS.getComicSize()) {
                ComicIndex -= 1;
                JOptionPane.showMessageDialog(null,
                        "Reached maximum Comic!!!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                ComicResult(ComicIndex);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Error!!!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnComicNextActionPerformed

    private void btnComicPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComicPreviousActionPerformed
        // TODO add your handling code here:
        try {
            ComicIndex -= 1;
            if (ComicIndex < 0) {
                ComicIndex += 1;
                JOptionPane.showMessageDialog(null,
                        "Reached minimum Comic!!!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                ComicResult(ComicIndex);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Reached minimum comic!!!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnComicPreviousActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (rbComic.isSelected()) {
            Comic comic = RS.SearchComics(txtSearch.getText());
            if (comic != null) {
                ComicIndex = RS.getComicIndex(txtSearch.getText());
                lblComic.setText("Comic " + (ComicIndex + 1) + " of " + RS.getComicSize());
                txtISBN.setText(comic.getISBN13Number());
                txtTitle.setText(comic.getTitleName());
                txtRental.setText("$" + String.format("%.2f", comic.RentalFeePD()));
                txtDeposit.setText("$" + String.format("%.2f", comic.DepositFee()));
                txtAreaInfo.setText(comic.AddInfo());
                txtAreaMsg.setText("Found and displayed item with the ISBN-13: " + txtSearch.getText());
            } else {
                txtAreaMsg.setText("No such ISBN-13 \"" + txtSearch.getText() + "\" in the data!");
            }

        } else {
            Rentee rentee = RS.SearchRentees(txtSearch.getText());
            if (rentee != null) {
                RenteeIndex = RS.getRenteeIndex(txtSearch.getText());
                lblRentee.setText("Rentee " + (RenteeIndex + 1) + " of " + RS.getRenteeSize());
                txtMemberID.setText(rentee.getMemberID());
                txtName.setText(rentee.getName());
                dtm.setRowCount(0);
                for (int i = 0; i < rentee.getComicsLoaned().length; i++) {
                    Comic comicsLoaned = RS.SearchComics(rentee.getComicsLoaned()[i]);
                    String ISBN = comicsLoaned.getISBN13Number();
                    String Title = comicsLoaned.getTitleName();
                    String Rental = "$" + String.format("%.2f", comicsLoaned.RentalFeePD());
                    String Deposit = "$" + String.format("%.2f", comicsLoaned.DepositFee());
                    Object[] objs = {ISBN, Title, Rental, Deposit};
                    dtm.addRow(objs);
                }
                txtAreaMsg.setText("Found and displayed item with the Member ID: " + txtSearch.getText());
            } else {
                txtAreaMsg.setText("No such Member ID \"" + txtSearch.getText() + "\" in the data!");
            }
        }
        txtSearch.setText("");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRenteePreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenteePreviousActionPerformed
        // TODO add your handling code here:
        try {
            RenteeIndex -= 1;
            if (RenteeIndex < 0) {
                RenteeIndex += 1;
                JOptionPane.showMessageDialog(null,
                        "Reached minimum Rentee!!!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                RenteeResult(RenteeIndex);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Error!!!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRenteePreviousActionPerformed

    private void btnRenteeNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenteeNextActionPerformed
        // TODO add your handling code here:
        try {
            RenteeIndex += 1;
            if (RenteeIndex >= RS.getRenteeSize()) {
                RenteeIndex -= 1;
                JOptionPane.showMessageDialog(null,
                        "Reached maximum Rentee!!!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                RenteeResult(RenteeIndex);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Error!!!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRenteeNextActionPerformed

    private void btnEarningStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEarningStatsActionPerformed
        // TODO add your handling code here:
        double Rental = 0;
        for (int i = 0; i < RS.getRenteeSize(); i++) {
            for (int y = 0; y < RS.DisplayRentees(i).getComicsLoaned().length; y++) {
                Comic comicsLoaned = RS.SearchComics(RS.DisplayRentees(i).getComicsLoaned()[y]);
                Rental += comicsLoaned.RentalFeePD();
            }
        }
        txtAreaMsg.setText(RS.DisplayEarnings(Rental));
    }//GEN-LAST:event_btnEarningStatsActionPerformed

    private void btnSaveExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveExitActionPerformed
        // TODO add your handling code here:
        RW.writeFile(RS.getRentees());
        JOptionPane.showMessageDialog(null, "Saving data...");
        JOptionPane.showMessageDialog(null, "Thank you for using Comic Rental"
                + "\nWe look forward to serve you in the near future");
        close();
    }//GEN-LAST:event_btnSaveExitActionPerformed

    public void ComicResult(int index) {
        txtISBN.setText(RS.DisplayComics(index).getISBN13Number());
        txtTitle.setText(RS.DisplayComics(index).getTitleName());
        txtRental.setText("$" + String.format("%.2f", RS.DisplayComics(index).RentalFeePD()));
        txtDeposit.setText("$" + String.format("%.2f", RS.DisplayComics(index).DepositFee()));
        txtAreaInfo.setText(RS.DisplayComics(index).AddInfo());
        lblComic.setText("Comic " + (index + 1) + " of " + RS.getComicSize());
    }

    public void RenteeResult(int index) {
        txtMemberID.setText(RS.DisplayRentees(index).getMemberID());
        txtName.setText(RS.DisplayRentees(index).getName());
        dtm.setRowCount(0);
        for (int i = 0; i < RS.DisplayRentees(index).getComicsLoaned().length; i++) {
            Comic comicsLoaned = RS.SearchComics(RS.DisplayRentees(index).getComicsLoaned()[i]);
            String ISBN = comicsLoaned.getISBN13Number();
            String Title = comicsLoaned.getTitleName();
            String Rental = "$" + String.format("%.2f", comicsLoaned.RentalFeePD());
            String Deposit = "$" + String.format("%.2f", comicsLoaned.DepositFee());
            Object[] objs = {ISBN, Title, Rental, Deposit};
            dtm.addRow(objs);
        }
        lblRentee.setText("Rentee " + (index + 1) + " of " + RS.getRenteeSize());
    }
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComicRentalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComicRentalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComicRentalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComicRentalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComicRentalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelComic;
    private javax.swing.JPanel PanelRentee;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnComicNext;
    private javax.swing.JButton btnComicPrevious;
    private javax.swing.JButton btnEarningStats;
    private javax.swing.JButton btnRenteeNext;
    private javax.swing.JButton btnRenteePrevious;
    private javax.swing.JButton btnSaveExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblComic;
    private javax.swing.JLabel lblRentee;
    private javax.swing.JRadioButton rbComic;
    private javax.swing.JRadioButton rbMember;
    private javax.swing.JTable tblRentee;
    private javax.swing.JTextArea txtAreaInfo;
    private javax.swing.JTextArea txtAreaMsg;
    private javax.swing.JTextField txtDeposit;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtMemberID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRental;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
